name: Test Build Next.js in Ubuntu

on:
    push:
        branches: ["**"]
    workflow_dispatch:

jobs:
  Build_Nextjs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22.19.0
            # Same as the system version

      - name: Check Node version
        run: node -v

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10.17.1

      - name: Check the pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build


  Run_Jest_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22.19.0
            # Same as the system version

      - name: Check Node version
        run: node -v

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10.17.1

      - name: Check the pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest Test
        run: pnpm test