name: Test Build Next.js in Ubuntu

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  Build_Nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Build
        run: pnpm build

  Jest_Test:
    runs-on: ubuntu-latest
    needs: Build_Nextjs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run Test
        run: pnpm test