name: Test Build Next.js in Ubuntu

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  Build_Nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/setup
      - run: pnpm build

  Jest_Test:
    runs-on: ubuntu-latest
    needs: Build_Nextjs # Only start this Jobs when the Build_Nextjs Job successful
    steps:
      - uses: ./.github/setup
      - run: pnpm test